**Notebook includes:** 
1. Import the data from a sav file
2. Data cleaning

In [1]:
### Libraries: 
#pip install pyreadstat

In [2]:
import pandas as pd
import pyreadstat
import numpy as np
import os

pd.set_option('display.max_columns', None)

In [3]:
# Set the current working directory 
os.chdir(os.getcwd())  
print(os.getcwd() )

C:\Users\marij\Documents\Master thesis\Upload Docs

# 1. Import data from sav file

In [4]:
# use read_sav to read SPSS file:
df, meta = pyreadstat.read_sav("Appendix_MariyaHristova_11250_Feb2023_raw_data.sav")

In [5]:
print("Shape: ", df.shape)
df.head()

Shape:  (674, 201)

,q1,q2,q3,q3_rec,q4,q5,q5_number,q5_rec,q6,q7,q8,q9,q9_com_rec,q9a,q10_1,q10_2,q10_3,q10_4,q10_5,q10_6,q10_7,q10_8,q10_9,q10_10,q10_11,q10_12,q10_13,q10_14,q10_15,q10_16,q10_17,q10_18,q10_19,q11,q12,q13,q14,q15_1,q15_2,q15_3,q15_4,q15_5,q15_6,q15_7,q15_8,q15_9,q15_10,q16_1,q16_2,q16_3,q16_4,q16_5,q16_6,q16_7,q16_8,q16_9,q16_10,q16_11,q16_12,q16_13,q16_14,q16_15,q16_16,q16_17,q16_18,q17,q17_rec,q17_rec2,q18,q18_rec,q19,q20_1,q20_2,q20_3,q20_4,q20_5,q20_6,q20_7,q20_8,q21,q22_1,q22_2,q22_3,q22_4,q22_5,q22_6,q22_7,q22a_1,q22a_2,q22b_1,q22c_1,q22c_2,q22c_3,q23,q24,q25_1,q25_2,q25_3,q25_4,q25_5,q25_6,q25_7,q26,q27,q28_1,q28_2,q28_3,q28_4,q28_5,q28_6,q28_7,q28_8,q28_9,q28_10,q29,q30,q31,q32,q32a,q33,q34,q35,q36,q37,q37_comment,q38,q39_1,q39_2,q39_3,q39_1_rec,q39_2_rec,q39_3_rec,q40_1,q40_2,q40_3,q40a,q41_1,q41_2,q41_3,q41_4,q41_5,q41_6,q41_7,q41_8,q41_9,q42_1,q42_2,q42_3,q42_4,q42_5,q42_6,q42_7,q43,q44_1,q44_2,q44_3,q44_4,q44_5,q44_6,q44_7,q44_8,q44_9,q44_10,q44_11,q44_12,q44_13,q44_14,q44a,q45_1,q45_2,q45_3,q45_4,q45_5,q45_6,q45_7,q46,q47,q48,q49,q50,q51,q52,q52_rec,q53,q22_1_rec,q22_2_rec,q22_3_rec,q22_4_rec,q22_5_rec,q22_6_rec,q22_7_rec,q22a_1_rec,q22a_2_rec,q22b_1_rec,q22c_1_rec,q22c_2_rec,q22c_3_rec,q22c_1_recc,q22c_2_recc,q22c_3_recc,PrimaryLast
0,1.0,1.0,32.0,6.0,2.0,65,64.0,8.0,2.0,99.0,2.0,7.0,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,16.0,0.0,18.0,0.0,9.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,5.0,6.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,6.0,6.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,4.0,,1.0,1.0,2.0,1.0,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,8.0,4.0,3.0,2.0,2.0,2.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0.0
1,1.0,1.0,32.0,6.0,2.0,65,64.0,8.0,2.0,99.0,2.0,7.0,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,16.0,0.0,18.0,0.0,9.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,5.0,6.0,0.0,0.0,9.0,0.0,11.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,5.0,5.0,1.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,4.0,,1.0,1.0,2.0,1.0,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,3.0,3.0,2.0,2.0,2.0,2.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0
2,1.0,1.0,33.0,6.0,2.0,65,65.0,8.0,2.0,99.0,2.0,7.0,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,16.0,0.0,18.0,0.0,9.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,5.0,6.0,0.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,6.0,6.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,3.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,2.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,4.0,,1.0,1.0,2.0,1.0,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,8.0,4.0,3.0,2.0,2.0,2.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0.0
3,1.0,1.0,33.0,6.0,2.0,65,65.0,8.0,2.0,99.0,2.0,7.0,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,15.0,16.0,0.0,18.0,0.0,9.0,2.0,1.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,24.0,0.0,0.0,0.0,0.0,5.0,6.0,0.0,0.0,9.0,0.0,11.0,12.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,5.0,5.0,1.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,3.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0,3.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,4.0,,1.0,1.0,2.0,1.0,NaN,2,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,3.0,3.0,2.0,2.0,2.0,2.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0
4,1.0,6.0,2.0,2.0,1.0,22,21.0,1.0,4.0,99.0,1.0,3.0,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,7.0,0.0,9.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,17.0,0.0,0.0,8.0,6.0,2.0,99.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,12.0,1.0,0.0,3.0,4.0,0.0,0.0,0.0,0.0,9.0,10.0,0.0,0.0,13.0,0.0,0.0,0.0,0.0,0.0,98.0,2013.0,5.0,1.0,1.0,99.0,3.0,2.0,4.0,4.0,3.0,3.0,2.0,2.0,2.0,5.0,4.0,99.0,4.0,3.0,3.0,4.0,4.0,4.0,3.0,3.0,4.0,99.0,2.0,1.0,1.0,2.0,1.0,4.0,4.0,4.0,2.0,2.0,2.0,1.0,0.0,3.0,4.0,0.0,6.0,7.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,,1.0,3.0,4.0,2.0,NaN,,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4.0,NaN,4.0,3.0,3.0,4.0,4.0,4.0,3.0,3.0,4.0,NaN,3.0,4.0,NaN,0.0

In [6]:
df.dtypes

q1             float64
q2             float64
q3             float64
q3_rec         float64
q4             float64
                ...
q22c_3_rec     float64
q22c_1_recc    float64
q22c_2_recc    float64
q22c_3_recc    float64
PrimaryLast    float64
Length: 201, dtype: object

# 2. Data Cleaning

## 2.1. NaNs, infinite values

In [7]:
# Calculate the percentage of missing values for each variable
data_missing_perc = pd.DataFrame(df.isna().sum() / len(df)).reset_index(drop = False)
data_missing_perc = data_missing_perc.rename(columns={0: 'Percentage of missing values', "index": "Question"}, errors="raise")
data_missing_perc.sort_values(by = 'Percentage of missing values', ascending = False )
data_missing_perc.sort_values(by = "Question")

        Question  Percentage of missing values
200  PrimaryLast                      0.000000
0             q1                      0.000000
14         q10_1                      0.000000
23        q10_10                      0.000000
24        q10_11                      0.000000
..           ...                           ...
9             q7                      0.035608
10            q8                      0.023739
11            q9                      0.050445
12    q9_com_rec                      0.902077
13           q9a                      0.658754

[201 rows x 2 columns]

In [8]:
# Make the nans to be consistent
df = df.replace('nan',np.NaN)
df=  df.replace('', np.NaN)

In [9]:
# Transform  all floats to int
numeric_cols = []
for i in df.columns[df.dtypes.apply(lambda c: np.issubdtype(c, np.number))]:
    numeric_cols.append(i)
#display(numeric_cols)
df[numeric_cols] = df[numeric_cols].astype(int,  errors='ignore')

In [10]:
print(df.dtypes.head(5))

q1        float64
q2        float64
q3        float64
q3_rec    float64
q4        float64
dtype: object

## 2.2 Encode the  variables

In [11]:
# Create a new dataframe, which is a copy of the original data 
df_replace = df.copy()

In [12]:
# Some of the binary in the data instead of the possible values 0, 1 
# have the value of the question instead, so we need to clean them and make them binary. 

q1_replace_map = {'q1': {2: 0, 1: 1}}

#q3 years since migration, some years are 1995, not since 20 years
q3_replace_map = {'q3': {1994: 0, 1995: 22, 2001: 16, 2002:15, 2007:10, 2008:9}}

q4_replace_map = {'q4': {2: 0, 1: 1}}
q6_replace_map = {'q6': {1:5, 2:6, 3:7, 4:4, 5:3, 6:2, 7:1, 8:0}}  
q7_replace_map = {'q7': {1:5, 2:6, 3:7, 4:4, 5:3, 6:2, 7:1, 99:0}}  
q8_replace_map = {'q8': {1:'bulgarian', 2:'foreign', 3:'double'}}  
q9_replace_map = {'q9': {1:'job', 2:'temp_job', 3:'education', 4:'family', 5:'green_card', 6: 'citiz_Canada', 7: "other"}} 
q9a_replace_map = {'q9a': {1:1, 2:0}}

### q10 
q10_2_replace_map = {'q10_2': {0:0, 2:1}}
q10_3_replace_map = {'q10_3': {0:0, 3:1}}
q10_4_replace_map = {'q10_4': {0:0, 4:1}}
q10_5_replace_map = {'q10_5': {0:0, 5:1}}
q10_6_replace_map = {'q10_6': {0:0, 6:1}}
q10_7_replace_map = {'q10_7': {0:0, 7:1}}
q10_8_replace_map = {'q10_8': {0:0, 8:1}}
q10_9_replace_map = {'q10_9': {0:0, 9:1}}
q10_10_replace_map = {'q10_10': {0:0, 10:1}}
q10_11_replace_map = {'q10_11': {0:0, 11:1}}
q10_12_replace_map = {'q10_12': {0:0, 12:1}}
q10_13_replace_map = {'q10_13': {0:0, 13:1}}
q10_14_replace_map = {'q10_14': {0:0, 14:1}}
q10_15_replace_map = {'q10_15': {0:0, 15:1}}
q10_16_replace_map = {'q10_16': {0:0, 1:1, 16:1}}
q10_17_replace_map ={'q10_17': {0:0, 1:1, 17:1}}
q10_18_replace_map = {'q10_18': {0:0, 1:1, 18:1}}
q10_19_replace_map = {'q10_19': {0:0, 19:1}}

q12_replacemap = {'q12': {1: 6, 2: 5, 3:4, 4:3, 5:2, 6:1}}
q13_replacemap = {'q13': {1:1, 2:0}}
q14_replacemap = {'q14': {1:1, 2:0, 99:0 }} # added 06/02/2021, merged No and I dont know into one category

# q15 
q15_2_replacemap = {'q15_2': {0:0, 2:1}}
q15_3_replacemap = {'q15_2': {0:0, 3:1}}
q15_4_replacemap = {'q15_4': {0:0, 4:1}}
q15_5_replacemap = {'q15_5': {0:0,1:1,5:1}}
q15_6_replacemap = {'q15_6': {0:0,1:1,6:1}}
q15_7_replacemap = {'q15_7': {0:0, 7:1}}
q15_8_replacemap = {'q15_8': {0:0,1:1,8:1}}
q15_9_replacemap = {'q15_9': {0:0,1:1,9:1}}


# First, I replace the missing values with 0, and then set everything else to 1.
df_replace['q15_10'] = df_replace['q15_10'].fillna(0)
df_replace.loc[df_replace['q15_10'] != 0, 'q15_10'] = 1.0

# q16 
q16_2_replace_map  = {'q16_2': {0:0, 2:1}}
q16_3_replace_map  = {'q16_3': {0:0, 3:1}}
q16_4_replace_map  = {'q16_4': {0:0, 4:1}}
q16_5_replace_map  = {'q16_5': {0:0, 5:1}}
q16_6_replace_map  = {'q16_6': {0:0, 6:1}}
q16_7_replace_map  = {'q16_7': {0:0, 7:1}}
q16_8_replace_map  = {'q16_8': {0:0, 8:1}}
q16_9_replace_map  = {'q16_9': {0:0, 9:1}}
q16_10_replace_map  = {'q16_10': {0:0, 10:1}}
q16_11_replace_map  = {'q16_11': {0:0, 11:1}}
q16_12_replace_map  = {'q16_12': {0:0, 12:1}}
q16_13_replace_map  = {'q16_13': {0:0, 13:1}}
q16_14_replace_map  = {'q16_14': {0:0, 14:1}}
q16_15_replace_map  = {'q16_15': {0:0, 15:1}}
q16_16_replace_map  = {'q16_16': {0:0, 16:1}}
q16_17_replace_map  = {'q16_17': {0:0, 17:1}}
q16_18_replace_map  = {'q16_18': {0:0, 18:1}}

q18_rec_replace_map = {'q18_rec' : {22:0}}


df_replace['q19'] = df_replace['q19'].fillna("unknown")
q19_replace_map  = {'q19': {1:"live_better", 2:"no_difference", 3: "live_worse", 99: "undecided" }}


df_replace['q21'] = df_replace['q21'].fillna("unknown")
q21_replace_map = {'q21' : {1: "yes_diff_attitude", 2: "some_extent_diff_attitude", 3: "no_diff_attitude", 99: "undecided_diff_attitude"}}

# Change 99 to 0: 
q22_1_replace_map = {'q22_1': {99: 0}}
q22_2_replace_map = {'q22_2': {99: 0}}
q22_3_replace_map = {'q22_3': {99: 0}}
q22_4_replace_map  = {'q22_4': {99: 0}}
q22_5_replace_map  = {'q22_5': {99: 0}}
q22_6_replace_map  = {'q22_6': {99: 0}}
q22_7_replace_map  = {'q22_7': {99: 0}}

# Changed 99 to 0: 
q22a_1_replace_map = {'q22a_1': {99: 0}}
q22a_2_replace_map = {'q22a_2': {99: 0}}
q22b_1_replace_map = {'q22b_1': {99: 0}}
q22c_1_replace_map = {'q22c_1': {99: 0}}
q22c_2_replace_map = {'q22c_2': {99: 0}}
q22c_3_replace_map = {'q22c_3': {99: 0}}

# Make q23 into dummies
q23_replace_map = {'q23': {1:"yes_local_friends", 2: "not_many_local_friends", 3: "no_local_friends", 99: "undecided_local_friends" }}

# Make q24 into dummies
q24_replace_map = {'q24': {1: "yes_talk_to_bg_comm", 2:"no_talk_to_bg_comm", 3: "not_often_talk_to_bg_comm" , 4: "no_bg_community", 99: "undecided"}}

q28_2_replace_map = {'q28_2': {0:0, 1:1, 2:1}}
q28_3_replace_map = {'q28_3': {0:0, 3:1}}
q28_4_replace_map = {'q28_4': {0:0, 1:1, 4:1}}
q28_5_replace_map = {'q28_5': {0:0, 1:1, 5:1}}
q28_6_replace_map = {'q28_6': {0:0, 1:1, 6:1}}
q28_7_replace_map = {'q28_7': {0:0, 1:1, 7:1}}
q28_8_replace_map = {'q28_4': {0:0, 8:1}}
q28_9_replace_map = {'q28_9': {0:0, 1:1, 9:1}}
q28_10_replace_map = {'q28_4': {0:0,  10:1}}

q29_replace_map = {'q29' : {1:1, 2:0}}
q30_replace_map = {'q30' : {1:1, 2:0}}

q33_replace_map = {'q33':{1:'bulgarian', 2: 'roma', 3: 'turkish', 4:'other'}}
q34_replace_map = {'q34': {1: 'married', 2: 'longterm_partner', 3:'unmarried', 4: 'divorced', 5: 'widow/er'}}
q35_replace_map = {'q35': {1: 'bulgarian', 2: 'host_country', 3: 'other_country', 4: 'no_husband/wife'}}


q36_replace_map = {'q36' : {1:1, 2:0}}

q37_comment_replace_map = {'q37_comment': {"едно": 1, "Едно": 1, '1':1, '2':2, '3':3, 
                                           'Едно дете.':1, 'Не чакам дате (въпреки коментарите на прияте': 0,
                                           '2 момче  и момиче':2, 'Не но синът ми е роден тук преди 14 год.': 1}}


q38_replace_map = {'q38' : {1:1, 2:0}}
q40a_replace_map = {'q40a' : {1:1, 2:0}}
q41_2_replace_map = {'q41_2' : {0:0, 2:1}}
q41_9_replace_map = {'q41_9' : {0:0, 9:1}}

q42_2_replace_map = {'q42_2' : {0:0, 2:1}}
q42_3_replace_map = {'q42_3' : {0:0, 3:1}}
q42_4_replace_map = {'q42_4' : {0:0, 4:1}}
q42_5_replace_map = {'q42_5' : {0:0, 5:1}}
q42_6_replace_map = {'q42_6' : {0:0, 6:1}}
q42_7_replace_map = {'q42_7' : {0:0, 7:1}}

q43_replace_map = {'q43' : {1:5, 2:4, 3:3, 4:2, 5:1}}

q45_2_replace_map = {'q45_2' : {0:0, 2:1}}
q45_3_replace_map = {'q45_3' : {0:0, 3:1}}
q45_4_replace_map = {'q45_4' : {0:0, 4:1}}
q45_5_replace_map = {'q45_5' : {0:0, 5:1}}
q45_6_replace_map = {'q45_6' : {0:0, 6:1}}
q45_7_replace_map = {'q45_7' : {0:0, 7:1}}

q47_replace_map = {'q47': {1: 'in_BG', 2: 'in_host_country', 3: 'in_another_country', 4: 'too_young', 5: 'no_school'}}

q48_replace_map = {'q48': {1: 'financial', 2: 'no_language', 3: 'work', 4: 'personal', 5: 'others'}}

q49_replace_map =  {'q49': {1: 'student', 2: 'worker', 3: 'employee', 4: 'freelancer', 5: 'owner', 
                            6: 'farmer', 7: 'unemployed', 8: 'pensioneer', 9: 'housewife_husband', 10: 'other'}}

q50_replace_map = {'q50': {1: 4 , 2: 3 , 3: 2, 4:1}}

q51_replace_map = {'q51': {1: 'public' , 2: 'private' , 3: 'not_employed'}}

In [13]:
df_replace.replace(q1_replace_map, inplace=True)
df_replace.replace(q3_replace_map, inplace=True)
df_replace.replace(q4_replace_map, inplace=True)
df_replace.replace(q6_replace_map, inplace = True) 
df_replace.replace(q7_replace_map, inplace = True) 
df_replace.replace(q8_replace_map, inplace = True) 
df_replace.replace(q9_replace_map, inplace=True)
df_replace.replace(q9a_replace_map, inplace=True)

### q10 
df_replace.replace(q10_2_replace_map, inplace=True)
df_replace.replace(q10_3_replace_map, inplace=True)
df_replace.replace(q10_4_replace_map, inplace=True)
df_replace.replace(q10_5_replace_map, inplace=True)
df_replace.replace(q10_6_replace_map, inplace=True)
df_replace.replace(q10_7_replace_map, inplace=True)
df_replace.replace(q10_8_replace_map, inplace=True)
df_replace.replace(q10_9_replace_map, inplace=True)
df_replace.replace(q10_10_replace_map, inplace=True)
df_replace.replace(q10_11_replace_map, inplace=True)
df_replace.replace(q10_12_replace_map, inplace=True)
df_replace.replace(q10_13_replace_map, inplace=True)
df_replace.replace(q10_14_replace_map, inplace=True)
df_replace.replace(q10_15_replace_map, inplace=True)
df_replace.replace(q10_16_replace_map, inplace=True)
df_replace.replace(q10_17_replace_map, inplace=True)
df_replace.replace(q10_18_replace_map, inplace=True)
df_replace.replace(q10_19_replace_map, inplace=True)

df_replace.replace(q12_replacemap, inplace=True)
df_replace.replace(q13_replacemap, inplace=True)
df_replace.replace(q14_replacemap, inplace=True)

# q15 
df_replace.replace(q15_2_replacemap, inplace = True)
df_replace.replace(q15_3_replacemap, inplace = True)
df_replace.replace(q15_4_replacemap, inplace = True)
df_replace.replace(q15_5_replacemap, inplace = True)
df_replace.replace(q15_6_replacemap, inplace = True)
df_replace.replace(q15_7_replacemap, inplace = True)
df_replace.replace(q15_8_replacemap, inplace = True)
df_replace.replace(q15_9_replacemap, inplace = True)


# q16 
df_replace.replace(q16_2_replace_map, inplace=True)
df_replace.replace(q16_3_replace_map, inplace=True)
df_replace.replace(q16_4_replace_map, inplace=True)
df_replace.replace(q16_5_replace_map, inplace = True)
df_replace.replace(q16_6_replace_map, inplace = True)
df_replace.replace(q16_7_replace_map, inplace = True)
df_replace.replace(q16_8_replace_map, inplace = True)
df_replace.replace(q16_9_replace_map, inplace = True)
df_replace.replace(q16_10_replace_map, inplace = True)
df_replace.replace(q16_11_replace_map, inplace = True)
df_replace.replace(q16_12_replace_map, inplace = True)
df_replace.replace(q16_13_replace_map, inplace = True)
df_replace.replace(q16_14_replace_map, inplace = True)
df_replace.replace(q16_15_replace_map, inplace = True)
df_replace.replace(q16_16_replace_map, inplace = True)
df_replace.replace(q16_17_replace_map, inplace = True)
df_replace.replace(q16_18_replace_map, inplace = True)

df_replace.replace(q18_rec_replace_map, inplace= True) 

#added 29/01/2021
df_replace.replace(q19_replace_map, inplace = True) 

df_replace.replace(q21_replace_map, inplace = True) 

# Changed 99 to 0: added 29/01/2021
df_replace.replace(q22_1_replace_map, inplace = True) 
df_replace.replace(q22_2_replace_map, inplace = True) 
df_replace.replace(q22a_2_replace_map, inplace = True) 
df_replace.replace(q22_3_replace_map, inplace = True) 
df_replace.replace(q22_4_replace_map, inplace = True) 
df_replace.replace(q22_5_replace_map, inplace = True) 
df_replace.replace(q22_6_replace_map, inplace = True) 
df_replace.replace(q22_7_replace_map, inplace = True) 

# Changed 99 to 0: added 29/01/2021
df_replace.replace(q22a_1_replace_map, inplace = True) 
df_replace.replace(q22a_1_replace_map, inplace = True) 
df_replace.replace(q22b_1_replace_map, inplace = True) 
df_replace.replace(q22c_1_replace_map, inplace = True) 
df_replace.replace(q22c_2_replace_map, inplace = True) 
df_replace.replace(q22c_3_replace_map, inplace = True) 

# Created dummies: added 29/01/2021
df_replace.replace(q23_replace_map, inplace = True) 

df_replace.replace(q24_replace_map, inplace = True) 

df_replace.replace(q28_2_replace_map, inplace= True) 
df_replace.replace(q28_3_replace_map, inplace = True)
df_replace.replace(q28_4_replace_map, inplace = True)
df_replace.replace(q28_5_replace_map, inplace = True)
df_replace.replace(q28_6_replace_map, inplace = True)
df_replace.replace(q28_7_replace_map, inplace = True)
df_replace.replace(q28_8_replace_map, inplace = True)
df_replace.replace(q28_9_replace_map, inplace = True)
df_replace.replace(q28_10_replace_map, inplace = True)

df_replace.replace(q29_replace_map, inplace = True)
df_replace.replace(q30_replace_map, inplace = True)
df_replace.replace(q33_replace_map, inplace = True)
df_replace.replace(q34_replace_map, inplace = True)
df_replace.replace(q35_replace_map, inplace = True)
df_replace.replace(q36_replace_map, inplace = True)


df_replace.replace(q37_comment_replace_map, inplace = True)


df_replace.replace(q38_replace_map, inplace = True)
df_replace.replace(q40a_replace_map, inplace = True)
df_replace.replace(q41_2_replace_map, inplace = True)
df_replace.replace(q41_9_replace_map, inplace = True)

df_replace.replace(q42_2_replace_map, inplace = True)
df_replace.replace(q42_3_replace_map, inplace = True)
df_replace.replace(q42_4_replace_map, inplace = True)
df_replace.replace(q42_5_replace_map, inplace = True)
df_replace.replace(q42_6_replace_map, inplace = True)
df_replace.replace(q42_7_replace_map, inplace = True)

df_replace.replace(q43_replace_map, inplace = True)

df_replace.replace(q45_2_replace_map, inplace = True)
df_replace.replace(q45_3_replace_map, inplace = True)
df_replace.replace(q45_4_replace_map, inplace = True)
df_replace.replace(q45_5_replace_map, inplace = True)
df_replace.replace(q45_6_replace_map, inplace = True)
df_replace.replace(q45_7_replace_map, inplace = True)


df_replace.replace(q47_replace_map, inplace = True)
df_replace.replace(q48_replace_map, inplace = True)

df_replace.replace(q49_replace_map, inplace = True)

df_replace.replace(q50_replace_map, inplace = True)
df_replace.replace(q51_replace_map, inplace = True)

display(df_replace.head(5))

,q1,q2,q3,q3_rec,q4,q5,q5_number,q5_rec,q6,q7,q8,q9,q9_com_rec,q9a,q10_1,q10_2,q10_3,q10_4,q10_5,q10_6,q10_7,q10_8,q10_9,q10_10,q10_11,q10_12,q10_13,q10_14,q10_15,q10_16,q10_17,q10_18,q10_19,q11,q12,q13,q14,q15_1,q15_2,q15_3,q15_4,q15_5,q15_6,q15_7,q15_8,q15_9,q15_10,q16_1,q16_2,q16_3,q16_4,q16_5,q16_6,q16_7,q16_8,q16_9,q16_10,q16_11,q16_12,q16_13,q16_14,q16_15,q16_16,q16_17,q16_18,q17,q17_rec,q17_rec2,q18,q18_rec,q19,q20_1,q20_2,q20_3,q20_4,q20_5,q20_6,q20_7,q20_8,q21,q22_1,q22_2,q22_3,q22_4,q22_5,q22_6,q22_7,q22a_1,q22a_2,q22b_1,q22c_1,q22c_2,q22c_3,q23,q24,q25_1,q25_2,q25_3,q25_4,q25_5,q25_6,q25_7,q26,q27,q28_1,q28_2,q28_3,q28_4,q28_5,q28_6,q28_7,q28_8,q28_9,q28_10,q29,q30,q31,q32,q32a,q33,q34,q35,q36,q37,q37_comment,q38,q39_1,q39_2,q39_3,q39_1_rec,q39_2_rec,q39_3_rec,q40_1,q40_2,q40_3,q40a,q41_1,q41_2,q41_3,q41_4,q41_5,q41_6,q41_7,q41_8,q41_9,q42_1,q42_2,q42_3,q42_4,q42_5,q42_6,q42_7,q43,q44_1,q44_2,q44_3,q44_4,q44_5,q44_6,q44_7,q44_8,q44_9,q44_10,q44_11,q44_12,q44_13,q44_14,q44a,q45_1,q45_2,q45_3,q45_4,q45_5,q45_6,q45_7,q46,q47,q48,q49,q50,q51,q52,q52_rec,q53,q22_1_rec,q22_2_rec,q22_3_rec,q22_4_rec,q22_5_rec,q22_6_rec,q22_7_rec,q22a_1_rec,q22a_2_rec,q22b_1_rec,q22c_1_rec,q22c_2_rec,q22c_3_rec,q22c_1_recc,q22c_2_recc,q22c_3_recc,PrimaryLast
0,1.0,1.0,32.0,6.0,0.0,65,64.0,8.0,6.0,0.0,foreign,other,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,9.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,6.0,6.0,live_better,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,no_diff_attitude,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,yes_local_friends,no_talk_to_bg_comm,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,NaN,bulgarian,married,host_country,1.0,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,pensioneer,1.0,not_employed,2.0,2.0,2.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0.0
1,1.0,1.0,32.0,6.0,0.0,65,64.0,8.0,6.0,0.0,foreign,other,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,9.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,5.0,5.0,live_better,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,no_diff_attitude,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,yes_local_friends,not_often_talk_to_bg_comm,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,4.0,NaN,bulgarian,married,host_country,1.0,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,employee,2.0,private,2.0,2.0,2.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0
2,1.0,1.0,33.0,6.0,0.0,65,65.0,8.0,6.0,0.0,foreign,other,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,9.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,6.0,6.0,live_better,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,no_diff_attitude,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,yes_local_friends,no_talk_to_bg_comm,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,NaN,bulgarian,married,host_country,1.0,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,pensioneer,1.0,not_employed,2.0,2.0,2.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,0.0
3,1.0,1.0,33.0,6.0,0.0,65,65.0,8.0,6.0,0.0,foreign,other,15.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,9.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,1984.0,1.0,5.0,5.0,live_better,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,no_diff_attitude,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,yes_local_friends,not_often_talk_to_bg_comm,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,4.0,NaN,bulgarian,married,host_country,1.0,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,employee,2.0,private,2.0,2.0,2.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,1.0
4,1.0,6.0,2.0,2.0,1.0,22,21.0,1.0,4.0,0.0,bulgarian,education,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,8.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,98.0,2013.0,5.0,1.0,1.0,undecided,3.0,2.0,4.0,4.0,3.0,3.0,2.0,2.0,some_extent_diff_attitude,5.0,4.0,0.0,4.0,3.0,3.0,4.0,4.0,4.0,3.0,3.0,4.0,0.0,not_many_local_friends,yes_talk_to_bg_comm,1.0,2.0,1.0,4.0,4.0,4.0,2.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,NaN,bulgarian,unmarried,no_husband/wife,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,5.0,4.0,NaN,4.0,3.0,3.0,4.0,4.0,4.0,3.0,3.0,4.0,NaN,3.0,4.0,NaN,0.0

In [14]:
df_replace.to_csv("Appendix_MariyaHristova_11250_Feb2023_data_for_exploration.csv",  index=False)

# Creating dummies/ Binary variables

In [15]:
## Creating dummys
# q8 
dummys_q8 = pd.get_dummies(df_replace.q8, prefix='q8')
df_replace = df_replace.drop(['q8'], axis=1)
df_replace = pd.concat([df_replace, dummys_q8], axis=1, join='inner')

In [16]:
#q9 
dummys_q9 = pd.get_dummies(df_replace.q9, prefix='q9')
df_replace = df_replace.drop(['q9'], axis=1)
df_replace = pd.concat([df_replace, dummys_q9], axis=1, join='inner')

In [17]:
#q11
dummys_q11 = pd.get_dummies(df_replace.q11, prefix='q11')
df_replace = df_replace.drop(['q11'], axis=1)
df_replace = pd.concat([df_replace, dummys_q11], axis=1, join='inner')

In [18]:
# q19 
dummys_q19 = pd.get_dummies(df_replace.q19, prefix='q19')
df_replace = df_replace.drop(['q19'], axis=1)
df_replace = pd.concat([df_replace, dummys_q19], axis=1, join='inner')

In [19]:
# q21
dummys_q21 = pd.get_dummies(df_replace.q21, prefix='q21')
df_replace = df_replace.drop(['q21'], axis=1)
df_replace = pd.concat([df_replace, dummys_q21], axis=1, join='inner')

In [20]:
# q23
dummys_q23 = pd.get_dummies(df_replace.q23, prefix='q23')
df_replace = df_replace.drop(['q23'], axis=1)
df_replace = pd.concat([df_replace, dummys_q23], axis=1, join='inner')

In [21]:
# q24
dummys_q24 = pd.get_dummies(df_replace.q24, prefix='q24')
df_replace = df_replace.drop(['q24'], axis=1)
df_replace = pd.concat([df_replace, dummys_q24], axis=1, join='inner')

In [22]:
# q33
dummys_q33 = pd.get_dummies(df_replace.q33, prefix='q33')
df_replace = df_replace.drop(['q33'], axis=1)
df_replace = pd.concat([df_replace, dummys_q33], axis=1, join='inner')

In [23]:
# q34
dummys_q34 = pd.get_dummies(df_replace.q34, prefix='q34')
df_replace = df_replace.drop(['q34'], axis=1)
df_replace = pd.concat([df_replace, dummys_q34], axis=1, join='inner')

In [24]:
# q35
dummys_q35 = pd.get_dummies(df_replace.q35, prefix='q35')
df_replace = df_replace.drop(['q35'], axis=1)
df_replace = pd.concat([df_replace, dummys_q35], axis=1, join='inner')

In [25]:
# q47
dummy_q47 = pd.get_dummies(df_replace.q47, prefix='q47')
df_replace = df_replace.drop(['q47'], axis=1)
df_replace = pd.concat([df_replace, dummy_q47], axis=1, join='inner')

In [26]:
# q48
dummy_q48 = pd.get_dummies(df_replace.q48, prefix='q48')
df_replace = df_replace.drop(['q48'], axis=1)
df_replace = pd.concat([df_replace, dummy_q48], axis=1, join='inner')

In [27]:
# q49
dummy_q49= pd.get_dummies(df_replace.q49, prefix='q49')
df_replace = df_replace.drop(['q49'], axis=1)
df_replace = pd.concat([df_replace, dummy_q49], axis=1, join='inner')

In [28]:
# q51 
dummy_q51= pd.get_dummies(df_replace.q51, prefix='q51')
df_replace = df_replace.drop(['q51'], axis=1)
df_replace = pd.concat([df_replace, dummy_q51], axis=1, join='inner')

In [29]:
### Create age of entry variable 
df_replace["age_of_entry"] = df_replace['q5'].astype(int)- df_replace['q3']
df_replace["age_of_entry"].head()

0    33.0
1    33.0
2    32.0
3    32.0
4    20.0
Name: age_of_entry, dtype: float64

In [30]:
df_replace['q5_rec'].value_counts()

4.0    104
1.0    102
5.0    102
2.0     91
3.0     90
6.0     77
8.0     54
7.0     54
Name: q5_rec, dtype: int64

## Derived variables

In [31]:
# make age categories binary variables 2023 year
#df_replace["q5_rec"].value_counts()

# 1- 18 to 22 years, 
# 2- from 23 to 25 years, 
# 3 - from 26 to 30 years,
# 4- from 31 to 35 years, 
# 5 - from 36 years to 40 years, 
# 6 - from 41 to 45 years, 
# 7- from 46 to 50 years,
# 8 - above 51

df_replace['q5'] = df_replace['q5'].astype(int)

df_replace['q5_age_18_25'] = 0
df_replace['q5_age_18_25'] = np.where((df_replace['q5'] >= 18) & 
                       (df_replace['q5'] <= 25), 1,0)

df_replace['q5_age_26_35'] = np.where((df_replace['q5'] >= 26) & 
                       (df_replace['q5'] <=35), 1,0)

df_replace['q5_age_36_50'] = np.where((df_replace['q5'] >= 36) & 
                       (df_replace['q5'] <= 50), 1,0)

df_replace['q5_above_51'] = np.where((df_replace['q5'] >= 51), 1,0)

In [32]:
print(df_replace['q5_age_18_25'].value_counts()) # 182
print(df_replace['q5_age_26_35'].value_counts()) # 192
print(df_replace['q5_age_36_50'].value_counts())
print(df_replace['q5_above_51'].value_counts())

0    492
1    182
Name: q5_age_18_25, dtype: int64
0    482
1    192
Name: q5_age_26_35, dtype: int64
0    430
1    244
Name: q5_age_36_50, dtype: int64
0    618
1     56
Name: q5_above_51, dtype: int64

In [33]:
# Create the target variables
df_replace['return'] = np.NaN 
df_replace.loc[df_replace['q27'] <= 2, 'return'] = '1'
df_replace.loc[df_replace['q27'] >= 3, 'return'] = '0'

In [34]:
# Create a variable education, which which chooses the higher value between q6 (Education in BG) and q7 ( Education abroad), i.r. education both in BG and abroad
#df_replace["q6"]
# df_replace[['q6','q7']].apply(np.max,axis=1).nunique()

df_replace["education"] = df_replace[['q6','q7']].apply(np.max,axis=1)
df_replace["education"]

df_replace = df_replace.drop(['q6'], axis=1) # avoid perfect collenearity

In [35]:
print(pd.crosstab(df_replace['return'], df_replace['education']))

# # Combined the categories Bachelor's or Masters and PhD into one category, because there were not enough observations
# eduaction_replace_map = {'education ': {5:5 , 6:5, 7: 5}} 
# df_replace.replace(eduaction_replace_map, inplace=True)

education  3.0  4.0  5.0  6.0  7.0
return
0            0   70  130  120   20
1            2   66   70   66   18

In [36]:
#drop/remove unnecessary variables 

df_replace = df_replace.drop(['q32a'], axis=1) # written answer # 32a. Do you have any recommendation or comment regarding the organization of the Bulgarian elections in the country you are in?

df_replace = df_replace.drop(['q37'], axis=1)  # I use 37_comment instead

df_replace = df_replace.drop(['q39_1_rec'], axis=1) # I use q39_1: age of first child 
df_replace = df_replace.drop(['q39_2_rec'], axis=1) # I use q39_3: age of second child
df_replace = df_replace.drop(['q39_3_rec'], axis=1) # I use 39_3: age of third child
df_replace = df_replace.drop(['q44a'], axis=1) # text comment about conversation topics with children
df_replace = df_replace.drop(['q46'], axis=1)  # Where are your children medically treated, if necessary?

df_replace = df_replace.drop(['q9_com_rec', 'q22_1_rec', 'q22_2_rec','q22_3_rec', # q9_com_rec: no question to the answers in the data
                              'q22_4_rec', 'q22_5_rec', 'q22_6_rec', 
                              'q22_7_rec', 'q22a_1_rec', 'q22a_2_rec', 
                               'q22b_1_rec', 'q22c_1_rec', 'q22c_2_rec', 
                               'q22c_3_rec', 'q22c_1_recc', 'q22c_2_recc', 
                                'q22c_3_recc', 'PrimaryLast'], axis = 1)  

# extra columns q22: 22.1 Urban planning and living conditions, they are duplicated with q22_1

df_replace = df_replace.drop(['q17'], axis = 1) # in which year you immigrated? 98 - i have not, 99 - temporarily, it does not makes sense, even if ot is 98, people have said the year

In [37]:
df_replace.dtypes

q1              float64
q2              float64
q3              float64
q3_rec          float64
q4              float64
                 ...
q5_age_26_35      int32
q5_age_36_50      int32
q5_above_51       int32
return           object
education       float64
Length: 241, dtype: object

In [38]:
# make object type into float 64 # q5, q37_comment, return 
df_replace[["q5"]] = df_replace[["q5"]].astype(float)
df_replace[["q37_comment"]] = df_replace[["q37_comment"]].astype(float)
df_replace[["return"]] = df_replace[["return"]].astype(float)
#df_replace.dtypes

In [39]:
# Create a combined category fot childen's location 
# First child - 	q40_1	1,2,3	In Bulgaria, In the country, where I currently live, In another country 
# Second child - 	q40_2	1,2,3	In Bulgaria, In the country, where I currently live, In another country 
# Third child - 	q40_3	1,2,3	In Bulgaria, In the country, where I currently live, In another country 

# 1  3 --> not in the same country 
# 2 --> same country 

df_replace['q40_1_child_loc_bg'] = np.where((df_replace['q40_1'] == 1), 1,0)
df_replace['q40_1_child_loc_same'] = np.where((df_replace['q40_1'] == 2), 1,0)
df_replace['q40_1_child_loc_dif'] = np.where((df_replace['q40_1'] == 3), 1,0)

df_replace['q40_2_child_loc_bg'] = np.where((df_replace['q40_2'] == 1), 1,0)
df_replace['q40_2_child_loc_same'] = np.where((df_replace['q40_2'] == 2), 1,0)
df_replace['q40_2_child_loc_dif'] =  np.where((df_replace['q40_2'] == 3), 1,0)

df_replace['q40_3_child_loc_bg'] = np.where((df_replace['q40_3'] == 1), 1,0)
df_replace['q40_3_child_loc_same'] = np.where((df_replace['q40_3'] == 2), 1,0)
df_replace['q40_3_child_loc_dif'] =  np.where((df_replace['q40_3'] == 3), 1,0)

print(df_replace['q40_1_child_loc_bg'].sum())
print(df_replace['q40_1_child_loc_same'].sum())
print(df_replace['q40_1_child_loc_dif'].sum())

print(df_replace['q40_2_child_loc_bg'].sum())
print(df_replace['q40_2_child_loc_same'].sum())
print(df_replace['q40_2_child_loc_dif'].sum())

print(df_replace['q40_3_child_loc_bg'].sum())
print(df_replace['q40_3_child_loc_same'].sum())
print(df_replace['q40_3_child_loc_dif'].sum())

8
160
6
2
82
2
0
12
0

In [40]:
df_replace['q40_child_BG'] = np.where((df_replace['q40_1_child_loc_bg'] == 1) |
                                      (df_replace['q40_2_child_loc_bg'] == 1) | 
                                      (df_replace['q40_3_child_loc_bg'] == 1), 1,0)

print(df_replace['q40_child_BG'].value_counts())

df_replace['q40_child_same'] = np.where((df_replace['q40_1_child_loc_same'] == 1) |
                                        (df_replace['q40_2_child_loc_same'] == 1) | 
                                        (df_replace['q40_3_child_loc_same'] == 1), 1,0)

print(df_replace['q40_child_same'].value_counts())


df_replace['q40_child_dif'] = np.where((df_replace['q40_1_child_loc_dif'] == 1) |
                                       (df_replace['q40_2_child_loc_dif'] == 1) | 
                                       (df_replace['q40_3_child_loc_dif'] == 1), 1,0)

print(df_replace['q40_child_dif'].value_counts())

0    666
1      8
Name: q40_child_BG, dtype: int64
0    512
1    162
Name: q40_child_same, dtype: int64
0    666
1      8
Name: q40_child_dif, dtype: int64

In [41]:
# Check if the variables are correctly created
#df_replace[df_replace['q40_child_same'] == 1][['q40_1', 'q40_2', 'q40_3']]
# df_replace[df_replace['q40_child_dif'] == 1][['q40_1', 'q40_2', 'q40_3']]
# df_replace[df_replace['q40_child_BG'] == 1][['q40_1', 'q40_2', 'q40_3']]

In [42]:
# drop the intermidiate variables:
df_replace = df_replace.drop(['q40_1_child_loc_bg', 'q40_1_child_loc_same', 'q40_1_child_loc_dif', 
                              'q40_2_child_loc_bg', 'q40_2_child_loc_same', 'q40_2_child_loc_dif', 
                              'q40_3_child_loc_bg', 'q40_3_child_loc_same', 'q40_3_child_loc_dif'], axis = 1)

In [43]:
# Citizenship variable
df_replace['q8_bulgarian'].shape # 674
df_replace['q8_bulgarian'].value_counts() # 168

df_replace['q8_double'].value_counts()  #120 
df_replace['q8_foreign'].value_counts() #32 

df_replace['q8_bg_double'] = np.where((df_replace['q8_bulgarian']> 0) | (df_replace['q8_double']> 0), 1, 0)
df_replace['q8_bg_double'] .value_counts()

1    626
0     48
Name: q8_bg_double, dtype: int64

In [44]:
print("Shape:" ,df_replace.shape)
df_replace.head()

Shape: (674, 245)

,q1,q2,q3,q3_rec,q4,q5,q5_number,q5_rec,q7,q9a,q10_1,q10_2,q10_3,q10_4,q10_5,q10_6,q10_7,q10_8,q10_9,q10_10,q10_11,q10_12,q10_13,q10_14,q10_15,q10_16,q10_17,q10_18,q10_19,q12,q13,q14,q15_1,q15_2,q15_3,q15_4,q15_5,q15_6,q15_7,q15_8,q15_9,q15_10,q16_1,q16_2,q16_3,q16_4,q16_5,q16_6,q16_7,q16_8,q16_9,q16_10,q16_11,q16_12,q16_13,q16_14,q16_15,q16_16,q16_17,q16_18,q17_rec,q17_rec2,q18,q18_rec,q20_1,q20_2,q20_3,q20_4,q20_5,q20_6,q20_7,q20_8,q22_1,q22_2,q22_3,q22_4,q22_5,q22_6,q22_7,q22a_1,q22a_2,q22b_1,q22c_1,q22c_2,q22c_3,q25_1,q25_2,q25_3,q25_4,q25_5,q25_6,q25_7,q26,q27,q28_1,q28_2,q28_3,q28_4,q28_5,q28_6,q28_7,q28_8,q28_9,q28_10,q29,q30,q31,q32,q36,q37_comment,q38,q39_1,q39_2,q39_3,q40_1,q40_2,q40_3,q40a,q41_1,q41_2,q41_3,q41_4,q41_5,q41_6,q41_7,q41_8,q41_9,q42_1,q42_2,q42_3,q42_4,q42_5,q42_6,q42_7,q43,q44_1,q44_2,q44_3,q44_4,q44_5,q44_6,q44_7,q44_8,q44_9,q44_10,q44_11,q44_12,q44_13,q44_14,q45_1,q45_2,q45_3,q45_4,q45_5,q45_6,q45_7,q50,q52,q52_rec,q53,q8_bulgarian,q8_double,q8_foreign,q9_citiz_Canada,q9_education,q9_family,q9_green_card,q9_job,q9_other,q9_temp_job,q11_1.0,q11_2.0,q11_3.0,q11_4.0,q11_5.0,q11_6.0,q11_7.0,q11_8.0,q11_9.0,q11_10.0,q11_11.0,q11_12.0,q11_13.0,q11_14.0,q11_15.0,q11_16.0,q11_17.0,q19_live_better,q19_live_worse,q19_no_difference,q19_undecided,q19_unknown,q21_no_diff_attitude,q21_some_extent_diff_attitude,q21_undecided_diff_attitude,q21_unknown,q21_yes_diff_attitude,q23_no_local_friends,q23_not_many_local_friends,q23_undecided_local_friends,q23_yes_local_friends,q24_no_bg_community,q24_no_talk_to_bg_comm,q24_not_often_talk_to_bg_comm,q24_undecided,q24_yes_talk_to_bg_comm,q33_bulgarian,q33_other,q33_roma,q33_turkish,q34_divorced,q34_longterm_partner,q34_married,q34_unmarried,q34_widow/er,q35_bulgarian,q35_host_country,q35_no_husband/wife,q35_other_country,q47_in_BG,q47_in_another_country,q47_in_host_country,q49_employee,q49_freelancer,q49_housewife_husband,q49_other,q49_owner,q49_pensioneer,q49_student,q49_unemployed,q49_worker,q51_not_employed,q51_private,q51_public,age_of_entry,q5_age_18_25,q5_age_26_35,q5_age_36_50,q5_above_51,return,education,q40_child_BG,q40_child_same,q40_child_dif,q8_bg_double
0,1.0,1.0,32.0,6.0,0.0,65.0,64.0,8.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1984.0,1.0,6.0,6.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,2.0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,33.0,0,0,0,1,0.0,6.0,0,0,0,0
1,1.0,1.0,32.0,6.0,0.0,65.0,64.0,8.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1984.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,4.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,33.0,0,0,0,1,0.0,6.0,0,0,0,0
2,1.0,1.0,33.0,6.0,0.0,65.0,65.0,8.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1984.0,1.0,6.0,6.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,4.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,2.0,4.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,2.0,2.0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,1,0,0,32.0,0,0,0,1,0.0,6.0,0,0,0,0
3,1.0,1.0,33.0,6.0,0.0,65.0,65.0,8.0,0.0,NaN,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,0.0,5.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1984.0,1.0,5.0,5.0,5.0,5.0,5.0,5.0,4.0,4.0,4.0,4.0,5.0,4.0,5.0,5.0,4.0,4.0,5.0,5.0,5.0,5.0,5.0,5.0,5.0,2.0,2.0,2.0,2.0,3.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,4.0,1.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,2.0,2.0,2.0,2.0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,1,0,32.0,0,0,0,1,0.0,6.0,0,0,0,0
4,1.0,6.0,2.0,2.0,1.0,22.0,21.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,2013.0,5.0,1.0,1.0,3.0,2.0,4.0,4.0,3.0,3.0,2.0,2.0,5.0,4.0,0.0,4.0,3.0,3.0,4.0,4.0,4.0,3.0,3.0,4.0,0.0,1.0,2.0,1.0,4.0,4.0,4.0,2.0,2.0,2.0,1.0,0.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,2.0,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,NaN,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,0,0,0,0,1,1,0,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,20.0,1,0,0,0,1.0,4.0,0,0,0,1

# Export data clean

In [45]:
print(os.getcwd())
df_replace.to_csv("Appendix_MariyaHristova_11250_Feb2023_data_clean.csv",  index=False)

C:\Users\marij\Documents\Master thesis\Upload Docs

# Map the variable names with the questions

In [46]:
# All the variables names
data_columns = pd.DataFrame(df_replace.columns)
data_columns

                  0
0                q1
1                q2
2                q3
3            q3_rec
4                q4
..              ...
240       education
241    q40_child_BG
242  q40_child_same
243   q40_child_dif
244    q8_bg_double

[245 rows x 1 columns]

In [47]:
# Import the file with the mapping of variable and question
map_variables = pd.read_csv("Appendix_MariyaHristova_11250_Feb2023_mapping.csv")
#map_variables.head()
binary_cols = map_variables.loc[(map_variables['Type of variable'] == "Binary")]["Variable"].tolist()
print("Number of binary columns: ", len(binary_cols))

numeric_cols = map_variables.loc[(map_variables['Type of variable'] == "Numeric")]["Variable"].tolist()
print("Number of numeric columns: ", len(numeric_cols)) 

ordinal_categorical_cols = map_variables.loc[(map_variables['Type of variable'] == "Ordinal categorical")]["Variable"].tolist()
print("Number of ordinal categorical columns: ", len(ordinal_categorical_cols))

nominal_categorical_cols = map_variables.loc[(map_variables['Type of variable'] == "Nominal categorical")]["Variable"].tolist()
print("Number of nominal categorical columns: ", len(nominal_categorical_cols))

print("Number of columns in the table:", df_replace.shape[1])

Number of binary columns:  189
Number of numeric columns:  11
Number of ordinal categorical columns:  48
Number of nominal categorical columns:  4
Number of columns in the table: 245